### ISSUE TITLE
Order of parameters in yaml files

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/roms-tools#189]
Currently, the parameters of a class are printed into the yaml file in alphabetical order, for instance:

```
---
roms_tools_version: 1.6.0
---
Grid:
  N: 20
  center_lat: 65
  center_lon: -18
  hc: 300.0
  hmin: 5.0
  nx: 30
  ny: 30
  rot: 20
  size_x: 800
  size_y: 800
  theta_b: 2.0
  theta_s: 5.0
  topography_source: ETOPO5
```

It would be more intuitive to leave them in their logical order, for instance
1. all horizontal grid parameters
2. all topography parameters
3. all vertical grid parameters

```
---
roms_tools_version: 1.6.0
---
Grid:
  nx: 30
  ny: 30
  size_x: 800
  size_y: 800
  center_lat: 65
  center_lon: -18
  rot: 20
  topography_source: ETOPO5
  hmin: 5.0
  N: 20
  theta_s: 5.0
  theta_b: 2.0
  hc: 300.0
```
