### ISSUE TITLE
`to_yaml` does not correctly handle pathlib Paths 

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/roms-tools#210]
When an object (e.g. `TidalForcing`) has a `source` attribute, and the user provides a `Path` instance, this is incorrectly serialised by `to_yaml`. For example:

```
TidalForcing:
  source:
    name: TPXO
    path: !!python/object/apply:pathlib._local.PosixPath
    - /Users/dafyddstephenson/Code/roms_tools_datasets
    - tpxo9.v2a.nc
  ntides: 14
  allan_factor: 2.0
  model_reference_date: '2000-01-01T00:00:00'
```
